# Generated by Django 4.1.2 on 2022-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
